import type { AdEvaluation } from '../types/evaluation.ts';

export const SAMPLE_DATA: AdEvaluation = {
  adName: "〇〇モバイル 春の乗り換えキャンペーン バナー広告",
  advertiser: "株式会社〇〇通信",
  industry: "通信",
  evaluatedAt: "2026-03-01T10:00:00Z",
  checkItems: [
    {
      id: 1,
      category: "通信速度表示",
      item: "ベストエフォートである旨の記載があるか",
      verdict: "OK",
      reason: "広告下部に「※本サービスはベストエフォート型です」の注記あり",
      improvement: null,
    },
    {
      id: 2,
      category: "通信速度表示",
      item: "実測値ではなく理論値であることが明示されているか",
      verdict: "NG",
      reason: "「最大速度1Gbps」の記載があるが、理論値である旨の注記がない",
      improvement: "「※表示の通信速度は技術規格上の最大値であり、実際の速度を示すものではありません」等の注記を追加",
    },
    {
      id: 3,
      category: "通信速度表示",
      item: "速度制限条件（データ上限等）の記載があるか",
      verdict: "NG",
      reason: "月間データ容量超過時の速度制限について記載なし",
      improvement: "「※月間データ容量超過後は最大128kbpsに制限されます」等の条件を明記",
    },
    {
      id: 4,
      category: "料金表示",
      item: "税込価格で表示されているか",
      verdict: "OK",
      reason: "全料金表示に「（税込）」が併記されている",
      improvement: null,
    },
    {
      id: 5,
      category: "料金表示",
      item: "キャンペーン価格の適用条件が明記されているか",
      verdict: "NG",
      reason: "「月額980円〜」の表示があるが、適用条件（新規契約限定、12ヶ月間のみ等）の記載なし",
      improvement: "「※新規契約の方限定。13ヶ月目以降は月額2,980円（税込）となります」等の条件を追記",
    },
    {
      id: 6,
      category: "料金表示",
      item: "初期費用・事務手数料の記載があるか",
      verdict: "OK",
      reason: "「事務手数料3,300円（税込）」の記載あり",
      improvement: null,
    },
    {
      id: 7,
      category: "料金表示",
      item: "解約金・違約金の記載があるか",
      verdict: "判定不可",
      reason: null,
      improvement: null,
    },
    {
      id: 8,
      category: "エリア・対応",
      item: "サービス提供エリアの制限に関する記載があるか",
      verdict: "OK",
      reason: "「※一部エリアではご利用いただけません。詳細は公式サイトをご確認ください」の注記あり",
      improvement: null,
    },
    {
      id: 9,
      category: "エリア・対応",
      item: "対応端末・動作環境の制限事項が記載されているか",
      verdict: "NG",
      reason: "対応端末の記載がなく、全端末で利用可能と誤認される恐れがある",
      improvement: "「※対応端末一覧は公式サイトをご確認ください」等のリンク・注記を追加",
    },
    {
      id: 10,
      category: "キャンペーン",
      item: "キャンペーン期間が明記されているか",
      verdict: "OK",
      reason: "「2026年3月1日〜3月31日」のキャンペーン期間が明記されている",
      improvement: null,
    },
    {
      id: 11,
      category: "キャンペーン",
      item: "特典の付与条件が明記されているか",
      verdict: "NG",
      reason: "「最大20,000ポイント還元」の表示があるが、達成条件の記載がない",
      improvement: "「※オプション3つ以上加入かつ12ヶ月継続利用が条件です」等の付与条件を明記",
    },
    {
      id: 12,
      category: "景品表示法",
      item: "優良誤認を招く表現がないか",
      verdict: "OK",
      reason: "品質・性能に関する表示は客観的事実に基づいており、誇大表現は見受けられない",
      improvement: null,
    },
    {
      id: 13,
      category: "景品表示法",
      item: "有利誤認を招く表現がないか",
      verdict: "NG",
      reason: "「業界最安値」と表示しているが、比較対象・調査時期の根拠が示されていない",
      improvement: "「※2026年2月時点、当社調べ。主要MNO4社のプラン比較」等の根拠を明示、または表現を「業界最安水準」に変更",
    },
    {
      id: 14,
      category: "景品表示法",
      item: "No.1表示に調査出典が明記されているか",
      verdict: "判定不可",
      reason: null,
      improvement: null,
    },
    {
      id: 15,
      category: "著作権・肖像権",
      item: "使用素材の権利処理が確認できるか",
      verdict: "OK",
      reason: "使用画像はすべてライセンス取得済みのストック素材であることを確認",
      improvement: null,
    },
  ],
};

export const SAMPLE_JSON = JSON.stringify(SAMPLE_DATA, null, 2);
